#################### I/O File paths ####################
## Absolute paths are recommended instead of relative paths
# workdir: Dir contains sample_read.list and will store result files.
workdir: "example"
#sample_reads_list_file: File name of sample_read.list. Must located in wirkdir
sample_reads_list_file: "1.sample.reads.list"
# Graph-based reference should be renamed as `Ref.gfa` and then placed in `workdir`

#################### Binary Paths ####################
## Absolute paths are recommended instead of relative paths
# Required:
stmsa: "misc/stmsa_0.2.1-ubuntu.20.04_amd64.out"
bcftools: "misc/bcftools"
vg: "misc/vg"
tabix: "misc/tabix"
# Optional but recommanded:
muscle3: "misc/muscle"
mafft: ""


#################### Filter Parameters ####################
# MAP_MINQ: minimal mapping-quality of each reads for giraffe-mapping in VG. Default is 5
MAP_MINQ: 5
# MAF: Remove alleles than lower than this value. This is necessary and will greatly reduce the complexity of SVs. Default is 0.01
MAF: 0.01
# max_missing_rate: Max missing rate allowed for each SNPs and SVs. 0 means no missing allowed and 1 means not filter by missing. Default is 0.3 (remove this site if more than 30% samples were missing)
max_missing_rate: 0.3
# Hard-filter: Min depth for each site is XX fold of mean depth of this sample. Default is 1/3 ~ 3
dp_min_fold: 0.333
dp_max_fold: 3
# Hard-filter: Min MAD(Minimum site allele depth) for each site is XX fold of mean depth of this sample. Default is 1/3 * 1/3
mad_min_fold: 0.111


#################### Realign Parameters ####################
# realign_extend: During realign progress, the near by SNP/SVs will be merged together before realign. Values that are too low or too large may lose some accuracy. Default is 10 and 1.
realign_extend_bp_max: 10
realign_extend_bp_min: 1


#################### More parameters ####################
# SV_min_length: Minimal length for SVs. Variat more than one base and smaller than this value will treated as InDels. Default is 50.
SV_min_length: 50
# realign_max_try_times_per_method: Default is 3.
realign_max_try_times_per_method: 3
# memory_tmp_dir: Temprory directory in memory. Must be a very fast disk. Left space can be smaller than 100Mb. Default is /run/user/USERID
memory_tmp_dir: "Default"
# mapper: can be either 'map' or 'gaffe'
mapper: 'gaffe'


#################### Performance & Resource ####################
# split_chr: (False/True). Weather split chr for parallel running. This is useful for multi-node clster. Not recommaned for single node. Default is False.
split_chr: False
# cores used in multi-threaded steps
core_realign: 10
cores_xg: 20
cores_snarls: 10
cores_map: 20
cores_pack: 10
cores_call: 10
cores_augment: 5
cores_avgdp: 6
# for minimizer/gaffe mapper
mem_xg: 60000
mem_snarls: 120000
mem_map: 40000
mem_pack: 100000
mem_call: 40000
mem_pgconvert: 60000
mem_augment: 70000
mem_avgdp: 20000
mem_realign: 20000


