
#################### Basic Parameters ####################
## Absolute paths are recommended for workdir and sample_reads_list_file
# workdir: Dir contains sample_read.list and will store result files.
#workdir: "example"
workdir: "/group_homes/lzu_public/home/share/zhengzy18/project/ath/6.graph"
# sample_reads_list_file: File name of sample_read.list. Must located in wirkdir.
sample_reads_list_file: "1.sample.reads.list"
# split_chr: (False or True). Weather split by chromosome for parallel running. This is useful for multi-node clster. This option can greatly reduce the memory usage in augment mode. If you only own one computer-node the recommended setting is False. Default is False.
split_chr: True
# mode: (genotype or augment). `genotype` mode will genotype SVs in the graph-genome. `augment` mode will extract novel SNPs and SVs for each sample. Default is `genotype`.
mode: "augment"
# Graph-based reference should be renamed as `Ref.gfa` and then placed in `workdir`. This value is not recommand for modifing! Default is `Ref`.
graph: 'Ref'


#################### binary paths ####################
## absolute paths are recommended instead of relative paths
## amd64
# required:
stmsa: "misc/stmsa_0.2.1-ubuntu.20.04_amd64.out"
bcftools: "misc/bcftools"
vg: "misc/vg"
tabix: "misc/tabix"
bgzip: "misc/bgzip"
seqs2identity: "src/gotoh/align"
# optional but highly recommanded:
mafft: "/group_homes/lzu_public/home/share/zhengzy18/software/mafft/mafft-7.490-with-extensions_built/bin/mafft"
muscle3: "misc/muscle"
# only for build_graph.pl
minigraph: "misc/minigraph"
seqs2identity: ""

## ARM64
# required:
#stmsa: "misc_arm/stmsa"
#bcftools: "misc_arm/bcftools"
#vg: "misc_arm/vg"
#tabix: "misc_arm/tabix"
#bgzip: "misc_arm/bgzip"
#seqs2identity: "src/gotoh/align"
## optional but highly recommanded:
#mafft: ""
#muscle3: "misc/muscle"
#seqs2identity: ""
# only for build_graph.pl
#minigraph: "misc/minigraph"


#################### Filter Parameters ####################
# MAP_MINQ: minimal mapping-quality of each reads for giraffe-mapping in VG. Default is 5.
MAP_MINQ: 5
# MAF: Remove alleles than lower than this value in genotype mode only. In genotype, this is necessary and will greatly reduce the complexity of SVs. Default is 0.01.
genotype_MAF: 0.01
# max_missing_rate: Max missing rate allowed for each SNPs and SVs. 0 means no missing allowed and 1 means not filter by missing. Default is 0.3 (remove this site if more than 30% samples were missing).
max_missing_rate: 0.3
# Hard-filter: Min depth for each site is XX fold of mean depth of this sample. Default is 1/3 ~ 3
dp_min_fold: 0.333
dp_max_fold: 10
# Hard-filter: Min MAD(Minimum site allele depth) for each site is XX fold of mean depth of this sample. Default is 1/3 * 1/3.
mad_min_fold: 0.111


#################### Realign Parameters ####################
# realign_extend: During realign progress, the near by SNP/SVs will be merged together before realign. Values that are too low or too large may lose some accuracy. Default is 10 and 1.
realign_extend_bp_max: 10
realign_extend_bp_min: 1


#################### More parameters ####################
# SV_min_length: Minimal length for SVs. Variat more than one base and smaller than this value will treated as InDels. Default is 50.
SV_min_length: 50
# realign_max_try_times_per_method: Default is 3.
realign_max_try_times_per_method: 3
# memory_tmp_dir: Temprory directory in memory. Must be a very fast disk. Left space can be smaller than 100Mb. Default is `Default` which for `/run/user/USERID`.
memory_tmp_dir: "Default"
# mapper: can be either 'map' or 'gaffe'
mapper: 'gaffe'
# aug_nonmut_min_cov: In augment mode, if the coverage of SV in reference allele is greater than this value will be treated as exists. Note this value is the first filter parameter, the further filter based on depth will be perfomed. Defalut is 0.8.
aug_nonmut_min_cov: 0.8
# aug_nomut_min_dp: In augment mode, if the average of depth of SV in reference allele is greater than this value will be treated as exists. Note this value is the first filter parameter, the further filter based on depth will be perfomed. Default is 3.
aug_nomut_min_dp: 3
# sv2pav_merge_identity_threshold:
sv2pav_merge_identity_threshold: 0.8
# ssindel: simple or small indel. Size default is 10.
ssindel_maxlen: 10
ssindel_maxallele: 3


#################### Performance & Resource ####################
# cores used in multi-threaded steps
cores_xg: 20
cores_snarls: 10
cores_map: 20
cores_pack: 10
cores_call: 10
cores_augment: 5
cores_avgdp: 6
cores_realign: 40
cores_aug_filldp: 2
# for minimizer/gaffe mapper
mem_xg: 60000
mem_snarls: 120000
mem_map: 40000
mem_pack: 100000
mem_call: 40000
mem_pgconvert: 60000
mem_augment: 70000
mem_avgdp: 20000
mem_realign: 20000
mem_aug_filldp: 15000


