
#################### binary paths ####################
## absolute paths are recommended instead of relative paths
## amd64
# required:
famsa: "famsa"
stmsa: "misc/stmsa_0.2.1-ubuntu.20.04_amd64.out"
muscle3: "muscle"
bcftools: "bcftools"
vg: "vg"
tabix: "tabix"
bgzip: "bgzip"

# Only for SV caller for raw long reads
minimap2: 'minimap2'
ngmlr: 'ngmlr'
sniffles: 'sniffles'
cutesv: 'cuteSV'
svim: 'svim'
picard: 'picard'
pbsv: 'pbsv'
nucmer: 'nucmer'
deltafilter: 'delta-filter'
showcoords: 'show-coords'
assemblytics: 'Assemblytics'
svim_asm: 'svim-asm'
bedtools: 'bedtools'
samtools: 'samtools'


# optional but highly recommanded:
mafft: "mafft"
# only for build_graph.pl
minigraph: "minigraph"

